AMBARI-17666. Fix python test error: cannot import name ensure_ssl_using_tls_v1 (adoroszlai via dlysnichenko)
(cherry picked from commit ed353f0a0bd8838f2be8ad5b6629068ed544e428)

Change-Id: I0db01a8c7220de9628f363540ce3766440308c9b