AMBARI-19218: Exception when running Slider view - java.lang.NoClassDefFoundError: org/apache/hadoop/yarn/api/protocolrecords/GetLabelsToNodesResponse (sangeetar)
(cherry picked from commit 21934340edd7d1fddd895258f0a7c174e0624919)

Change-Id: Id7570fb0f6f245b2d02efbbfee9ac7c8c159e4b3